### PR TITLE
remove calling systemd-sleep-grub

### PR DESCRIPTION
**Pull request by tlei**
This is now in contained in a grub2 plugin and is not needed anymore.
See boo#941758 or boo#991350

### CODE REVIEW

**Comment by fbuihuu** [comment]
@tlei, thanks for the suggested changes.

However this repo is mainly used as patch queues and we don't merge foreign branches in it, at least for now.

Could you submit your changes to systemd-maintainers@suse.de instead via patches ?

Thanks.

**Comment by fbuihuu** [comment]
@tlei, actually your changes is equivalent to the drop of commit 65497aaeb576f9b55dc4778ed06dfbfd86e6c18a, right ?

**Comment by tlei** [comment]
@fbuihuu, thanks for the information about this repo. Sorry for using this, I just found it and it looked promising....

It is not really a revert for 65497aa. I think the lines

ConditionKernelCommandLine=resume

have to be preserved. Otherwise, it would be possible to call hibernate without a corresponding resume-device (But this is just my feeling, it might be wrong).

I will resubmit the patch at systemd-maintainers@suse.de.

If it is no problem, I would like to leave this PR open until the change has reached at least SLE12-SP2.

**Comment by fbuihuu** [comment]
On 08/08/2016 06:30 PM, tlei wrote:
> @fbuihuu <https://github.com/fbuihuu>, thanks for the information about
> this repo. Sorry for using this, I just found it and it looked promising....
> 

No problem.

> It is not really a revert for 65497aa
> <https://github.com/openSUSE/systemd/commit/65497aaeb576f9b55dc4778ed06dfbfd86e6c18a>.
> I think the lines
> 
> ConditionKernelCommandLine=resume
> 
> have to be preserved. Otherwise, it would be possible to call hibernate
> without a corresponding resume-device (But this is just my feeling, it
> might be wrong).

Indeed, however I'm wondering if this case is not already handled
systemd-sleep itself: if a resume device is not setup then the tool
should fail by its own, no ?

resume= kernel option is probably distro specific so I don't think
upstream would rely on it.

Anyway I'll drop the patch and you can cook up a new patch which
adds/restores the command line condition only if you think it's needed.

> 
> I will resubmit the patch at systemd-maintainers@suse.de
> <mailto:systemd-maintainers@suse.de>.
> 

Thanks !

> If it is no problem, I would like to leave this PR open until the change
> has reached at least SLE12-SP2.
> 

If you prefer that way, we'll let this PR open until this is entirely
solved.

**Comment by tlei** [comment]
sorry, I sent my patch to the ml before your last answer. I now understand what you want (first revert 65497aa, then readd  ConditionKernelCommandLine=resume only if it es really needed. I checked with my system and that is fine for me. I will close this PR and sent a corresponding comment and patch as response to the ml.

**Pull request closed without merging**
